version: '3.8'

services:
  # Spring Boot application (cluvr-noti)
  spring:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cluvr-noti
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - cluvr-net
  mongo:
    restart: always
    image: mongo:6.0
    container_name: cluvr-mongo
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 5s
      retries: 5
      start_period: 10s
    ports:
      - "27017:27017"
    networks:
      - cluvr-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # 내부 AMQP 통신 포트 (코드에서 이 포트로 접속함)
      - "15672:15672"   # 웹 대시보드 GUI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

networks:
  cluvr-net:
    driver: bridge
