# Notification 서버 설정
server:
  error:
    include-message: always
  port: 8082

spring:
  application:
    name: cluvr

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}

  data:
    mongodb:
      host: localhost
      port: 27017
      database: cluvr

jwt:
  secret:
    key:
  expirationMs: 3600000

# Cognito 설정
cognito:
  userPoolId: ${USER_POOL_ID}
  jwkSetUri: https://cognito-idp.us-west-2.amazonaws.com/${USER_POOL_ID}/.well-known/jwks.json

# AWS 설정
cloud:
  aws:
    region:
      static: us-west-2
    credentials:
      access-key: ${ACCESS_AWS}
      secret-key: ${SECRET_AWS}

# 로깅 설정
logging:
  level:
    root: INFO
    software.amazon.awssdk: DEBUG
    software.amazon.awssdk.auth: DEBUG
    com.amazonaws: DEBUG
    com.example.cluvrapi: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

api:
  server:
    base-url: https://api.cluvr.co.kr
