# Notification 서버 설정
server:
  error:
    include-message: always
  port: 8082

spring:
  application:
    name: cluvr

  rabbitmq:
    host: ${RMQ_HOST}
    port: ${RMQ_PORT}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}

  data:
    mongodb:
      host: localhost
      port: 27017
      database: cluvr

jwt:
  secret:
    key:
  expirationMs: 3600000

# Cognito 설정
cognito:
  userPoolId: ${USER_POOL_ID}
  jwkSetUri: https://cognito-idp.us-west-2.amazonaws.com/${USER_POOL_ID}/.well-known/jwks.json

# AWS 설정
cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

# 로깅 설정
logging:
  level:
    root: info
    com.example: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

api:
  server:
    base-url: http://localhost:8080
